version: "3"

services:
  c0:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./:/src
    command:
      - bash
      - -c
      - |
        set -e
        mkdir -p /app
        rsync -a --exclude 'target' /src/* /app/
        cd /app
        cargo run --release --bin bot -- --config-path /app/etc/c0.toml
    ports:
      - "8080:8080"
      - "8090:8081"
  c1:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./:/src
    command:
      - bash
      - -c
      - |
        set -e
        mkdir -p /app
        rsync -a --exclude 'target' /src/* /app/
        cd /app
        cargo run --release --bin bot -- --config-path /app/etc/c1.toml
    ports:
      - "8081:8080"
      - "8091:8081"
  s0:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./:/src
    command:
      - bash
      - -c
      - |
        set -e
        mkdir -p /app
        rsync -a --exclude 'target' /src/* /app/
        cd /app
        cargo run --release --bin bot -- --config-path /app/etc/s0.toml
    ports:
      - "8082:8080"
      - "8092:8081"
  s1:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./:/src
    command:
      - bash
      - -c
      - |
        set -e
        mkdir -p /app
        rsync -a --exclude 'target' /src/* /app/
        cd /app
        cargo run --release --bin bot -- --config-path /app/etc/s1.toml
    ports:
      - "8083:8080"
      - "8093:8081"
