id="c0"
maxrouteweight=10
loglevel="info"
ticketexpiration=10000
broadcastexpiration=10000
backlog_period=10

[public_http]
host="0.0.0.0"
port=8080
endpoint="/"
tracing=false
secret="01234567890123456789012345678901"

[private_http]
host="0.0.0.0"
port=8081
tracing=false
ticket_sync_endpoint="/ticket/sync"
ticket_async_endpoint="/ticket/async"

[peer.s0]
url="http://s0:8080/"
polling=true

[peer.s1]
url="http://s1:8080/"
polling=true

[ping.c1]
delay=1
destination_id="c1"
