secret="01234567890123456789012345678901"
id="docker-bot4"
host="0.0.0.0"
port=8080
endpoint="/"
maxrouteweight=10
tracing=false
loglevel="info"

[peer.docker-bot3]
url="http://bot3:8080/"
polling=false
