secret="01234567890123456789012345678901"
id="docker-bot3"
host="0.0.0.0"
port=8080
endpoint="/"
maxrouteweight=10
tracing=false
loglevel="info"

[peer.docker-bot2]
url="http://bot2:8080/"
polling=true

[peer.docker-bot4]
url="http://bot4:8080/"
polling=false