id="docker-bot0"
maxrouteweight=10
loglevel="info"
ticketexpiration=10000
broadcastexpiration=10000

[public_http]
host="0.0.0.0"
port=8080
endpoint="/"
tracing=false
secret="01234567890123456789012345678901"

[private_http]
host="0.0.0.0"
port=8081
tracing=false
ticket_sync_endpoint="/ticket/sync"
ticket_async_endpoint="/ticket/async"

[peer.docker-bot1]
url="http://bot1:8080/"
polling=false

[ping.docker-bot4]
delay=1
destination_id="docker-bot4"

# [trace.docker-bot4]
# delay=10
# destination_id="docker-bot4"
# request_id="bot4"
